---
title: "Pre-post fire veg indices - Function Lesson"
author: "Leah A. Wasser"
date: "3/6/2017"
output: html_document
---


# Setup R

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
# set working dir
setwd("~/Documents/earth-analytics")

# load spatial packages
library(raster)
library(rgdal)
library(rgeos)
library(RColorBrewer)
# turn off factors
options(stringsAsFactors = F)

# set colors

nbr_colors = c("palevioletred4","palevioletred1","ivory1","seagreen1","seagreen4")
ndvi_colors = c("brown","ivory1","seagreen1","seagreen4")

```

# Import Landsat data - Julian day 189


```{r cars}
# get list of tif files
all_landsat_bands <- list.files("data/week6/Landsat/LC80340322016189-SC20170128091153/crop",
                                pattern=glob2rx("*band*.tif$"),
                                full.names = T) # use the dollar sign at the end to get all files that END WITH

# stack the data (create spatial object)
landsat_stack_csf <- stack(all_landsat_bands)

```

## Calculate NDVI - pre-fire

```{r create-ndvi}
# calculate normalized index - NDVI
landsat_ndvi <- (landsat_stack_csf[[5]] - landsat_stack_csf[[4]]) / (landsat_stack_csf[[5]] + landsat_stack_csf[[4]])

# create classification matrix
# note i line it up like this so it looks more like the arcgis reclass table! 
reclass <- c(-1, -.2, 1,
             -.2, .2, 2,
             .2, .5, 3,
             .5, 1, 4)
# reshape the object into a matrix with columns and rows
reclass_m <- matrix(reclass,
                    ncol=3,
                    byrow=TRUE)

ndvi_classified <- reclassify(landsat_ndvi,
                             reclass_m)

# set colors
the_colors = c("palevioletred4","palevioletred1","ivory1","seagreen1","seagreen4")
# plot classified data
plot(ndvi_classified,
     box=F, axes=F, legend=F,
     main="NDVI - Pre fire")
legend(ndvi_classified@extent@xmax, ndvi_classified@extent@ymax,
       legend=c("class one", "class two", "class three"),
       fill = the_colors, bty="n", xpd=T)


### export NDVI raster with unique name 
writeRaster(x = landsat_ndvi,
            filename="data/week6/outputs/landsat_ndvi.tif",
            format = "GTiff", # save as a tif
            datatype='INT2S', # save as a INTEGER rather than a float
            overwrite = T)  # OPTIONAL - be careful. this will OVERWRITE previous files.

```

## Calculate Normalized Burn Ratio (NBR) - Pre fire

```{r calculate-plot-nbr}

# calculate normalized index = NBR
landsat_nbr <- (landsat_stack_csf[[4]] - landsat_stack_csf[[7]]) / (landsat_stack_csf[[4]] + landsat_stack_csf[[7]])

# create classification matrix
reclass <- c(-1.0, -.1, 1,
             -.1, .1, 2,
             .1, .27, 3,
             .27, .66, 4,
             .66, 1.3, 5)
# reshape the object into a matrix with columns and rows
reclass_m <- matrix(reclass,
                ncol=3,
                byrow=TRUE)

nbr_classified <- reclassify(landsat_nbr,
                     reclass_m)

# plot classified data
plot(ndvi_classified,
     box=F, axes=F, legend=F,
     main="Landsat NBR - Pre Fire \n Julian Day 189")
legend(nbr_classified@extent@xmax-100, nbr_classified@extent@ymax,
       c("Enhanced Regrowth", "Unburned", "Low Severity", "Moderate Severity", "High Severity"),
       fill=rev(the_colors),
       cex=.9, bty="n", xpd=T)

```

## Open & Process Post-fire data

```{r pressure, echo=FALSE}

#### Function: get tif files, make stack ####
# get list of tif files
all_landsat_bands_post <- list.files("data/week6/Landsat/LC80340322016205-SC20170127160728/crop",
                                pattern=glob2rx("*band*.tif$"),
                                full.names = T) # use the dollar sign at the end to get all files that END WITH

# stack the data (create spatial object)
landsat_stack_csf_post <- stack(all_landsat_bands_post)


# then use overlay to calculate NDVI rather than raster math which is inefficient
# landsat_ndvi_post <- overlay(landsat_stack_csf_post[[5]], landsat_stack_csf_post[[4]], 
#                        fun=calculate_normalized_index)

```

## Calculate NDVI - post-fire

```{r}
# calculate NDVI (the way they've been doing it is inefficient but they don't know functions yet)
landsat_ndvi_post <- (landsat_stack_csf_post[[5]] - landsat_stack_csf_post[[4]]) / (landsat_stack_csf_post[[5]] + landsat_stack_csf_post[[4]])


# create classification matrix
# note i line it up like this so it looks more like the arcgis reclass table! 
reclass <- c(-1, -.2, 1,
             -.2, .2, 2,
             .2, .5, 3,
             .5, 1, 4)
# reshape the object into a matrix with columns and rows
reclass_m <- matrix(reclass,
                    ncol=3,
                    byrow=TRUE)

ndvi_classified_post <- reclassify(landsat_ndvi_post,
                              reclass_m)

#### Plot with legend it's so annoying to do this over and over ####
plot(ndvi_classified_post,
     box=F, axes=F, legend=F,
     main="NDVI - Post Fire",
     col=ndvi_colors)
# par(xpd=T) # you may want to modify par here so this may not be an ideal function
legend(ndvi_classified_post@extent@xmax, ndvi_classified_post@extent@ymax,
       legend=c("No Vegetation", "Low Greenness", "Medium Greenness", "High Greeness"),
       fill = ndvi_colors, bty="n", xpd=T)



### Optional -- export NDVI raster with unique name 
writeRaster(x = ndvi_classified_post,
            filename="data/week6/outputs/landsat_ndvi_post.tif",
            format = "GTiff", # save as a tif
            datatype='INT2S', # save as a INTEGER rather than a float
            overwrite = T)  # OPTIONAL - be careful. this will OVERWRITE previous files.

plot(landsat_ndvi,
     main="Landsat derived NDVI\n 23 July 2016")


```

## Calculate NBR post fire 
Next, calculate Normalized Burn Ratio (NBR).

```{r calculate-plot-nbr}

# calculate normalized index = NBR
landsat_nbr_post <- (landsat_stack_csf_post[[5]] - landsat_stack_csf_post[[7]]) / (landsat_stack_csf_post[[5]] + landsat_stack_csf_post[[7]])
plot(landsat_nbr_post)
# create classification matrix
reclass <- c(-1.0, -.1, 1,
             -.1, .1, 2,
             .1, .27, 3,
             .27, .66, 4,
             .66, 1.3, 5)
# reshape the object into a matrix with columns and rows
reclass_m <- matrix(reclass,
                ncol=3,
                byrow=TRUE)

nbr_classified_post <- reclassify(landsat_nbr_post,
                     reclass_m)

# plot classified data
# note i've flipped the legend order here. We don't have to do that. 
plot(nbr_classified_post,
     box=F, axes=F, legend=F,
     col=nbr_colors,
     main="Landsat NBR - Post Fire \n Julian Day 205")
legend(nbr_classified@extent@xmax-100, nbr_classified@extent@ymax,
       c("Enhanced Regrowth", "Unburned", "Low Severity", "Moderate Severity", "High Severity"),
       fill=rev(the_colors),
       cex=.9, bty="n", xpd=T)


writeRaster(x = nbr_classified,
              filename="data/week6/outputs/nbr_classified_post.tif",
              format = "GTiff", # save as a tif
              datatype='INT2S', # save as a INTEGER rather than a float
              overwrite = T)

```