---
layout: single
title: "GEOG 4563 & 5563 - Earth Analytics: Spring 2017 Syllabus"
excerpt: "."
authors: ['Leah Wasser']
category: [course-materials]
permalink: /course-materials/earth-analytics/earth-analytics-syllabus/
nav-title: 'Course Syllabus'
sidebar:
  nav: earth-analytics-2017
author_profile: false
comments: false
---
 

## Lead Instructor

Dr. Leah A Wasser
Office. S346 SEEC
Ph. 303.735.4637
leah.wasser@colorado.edu

<div class='notice--success' markdown="1">

# Where & When

* **Teaching Assistant:** Sepideh Khanghah
* **Time:** Wednesday 3:00 pm -  5:50 pm
* **Location:** SEEC S125

**Contributing Instructors:**

  </div>

## Course Description
This advanced, multidisciplinary course will address major questions in Earth
science and teach students to use the analytical tools necessary to undertake
exploration of ‘big scientific data’. This course is desiend for upper level (junior /
senior level) undergraduate students and graduate students.

Throughout the course we will focus on addressing questions in science using
data and computationally intensive approaches. We will use a suite of different
types of publically available data including:

* various types of remote sensing data (spectral and lidar),
* data collected from large *in situ* (on the ground) sensor networks maintained
through organizations such as USGS and NOAA,
* social media data, and
* demographic (census) data.

## Learning Outcomes

At the end of this course you will be able to:

* Open and visualize various types of data using the `R` programming languages.
* Navigate and use the `RStudio` environment for `R`.
* Describe and apply several approaches to efficient computing including parallelization

## Grading
Grading will be based on the following course assignments. Late assignments will
receive a 10% deduction per 24-hour period after the due date/time.

| Assignment  | Percent of Credit   |
|---|---|---|---|---|
| Exercises | 25% |
| Mid Term Presentation | 20% |
| Final Group Presentation | 20% |
| Final Project Submission | 20%  |
| Class Participation | 15% |


## Attendance:

Attendance is required for all class sessions. In the event that you must miss a class due
to a university-approved activity, illness, injury, family emergency, or religious
observance, you must notify me, preferably before the day of class, and the absence
will be excused. Students will be given a reasonable amount of time to make up the
work based on the type of assignment missed and the reason for their absence.
Unexcused absences will affect the student’s grade because regular
participation is a requirement of this course.


## Readings

NOTE, readings are subject to change or additional ones added. Appropriate
notice will be given if readings do change.
