---
layout: single
title: "Working with function arguments"
excerpt: " ."
authors: ['Max Joseph', 'Software Carpentry',  'Leah Wasser']
modified: '`r format(Sys.time(), "%Y-%m-%d")`'
category: [course-materials]
class-lesson: ['automating-your-science-r']
permalink: /course-materials/earth-analytics/week-8/function-arguments-r/
nav-title: 'Function arguments'
week: 8
sidebar:
  nav:
author_profile: false
comments: true
order: 5
---


{% include toc title="In This Lesson" icon="file-text" %}

<div class='notice--success' markdown="1">

## <i class="fa fa-graduation-cap" aria-hidden="true"></i> Learning Objectives

After completing this tutorial, you will be able to:

* Define the purpose of a function argument.
* Use default vs. required function arguments in a function.

## <i class="fa fa-check-square-o fa-2" aria-hidden="true"></i> What you need

You will need a computer with internet access to complete this lesson.

</div>

#  Modularize your code

Looking at the code - break up into discrete tasks...

Find files < 2 lines
Calculate indices < 4 ??
Reclassify < 3 lines
plot stuff <- 8-10 lines + defining colors
save raster  < -  5 lines


|  Task | # of lines of code  |
|---|---|---|---|---|
| Find Files | 2 Lines |
| Calculate Indices   | 4 Lines  |
| Reclassify  | 3 lines  |
| Plot raster  | 3 lines  |
|===
| Save Raster   | 5 lines |


R is object oriented programming language
`c` is a primitive function  based on the programming language `C`


Parts of the function
1. name
2. arguments
3. body

Quote -- 2 hard things - cache validation & naming things...


# Function names --



3 tips to making good functions

1. express intent with the function name
2. be nice to humans
3. Make functions self-contained
4. TOO TAST

this is where the basmati rice picture might be nice...

* function names: should be a verb - tell you what the function does


## Document the function

* be sure to update comments if you change things
* Make your function self-contained
  * good example of using a variable that is not an input in the function itself...


## Self contained functions

Use maxes graphic - input --  function -- output

robust to standard global enviornment




****
piping function

32 %>%
  function() %>%
  function()



Defining expressive code
  
