#!/usr/bin/env bash
set -e # halt script on error

# create a development _config.yml file and comment out url
cp _config.yml _config-dev.yml
sed -i -e 's/"http:\/\/earthdatascience.org"/#"http:\/\/earthdatascience.org"/g' _config.yml

# build the site with that url
bundle exec jekyll build --config _config_dev.yml
bundle exec htmlproofer --url-swap "\{\{ site.url \}\}/images:/images" ./_site --file-ignore /example-leaflet-maps/ --http-status-ignore "301"
