---
layout: single
title: "Earth Lab Internship - Summer 2017 Syllabus"
excerpt: "The Earth Lab internship course syllabus."
authors: ['Mollie Buckland']
category: [course-materials]
permalink: /course-materials/internship/
nav-title: 'Syllabus'
dateCreated: 2017-05-10
modified: '`r format(Sys.time(), "%Y-%m-%d")`'
module-title: 'Earth Lab Internship '
module-nav-title: 'Internship'
module-description: 'The Earth Lab internship provides undergraduate students at the University of
Colorado Boulder with a real-world data intensive academic experience through
work on a science project.'
module-type: 'class'
course: "internship"
module-type: 'overview'
course: "internship"
sidebar:
  nav:
author_profile: false
comments: true
order: 1
topics:
---

{% include toc title="In This Lesson" icon="file-text" %}

The Earth Lab internship provides undergraduate students at the University of
Colorado Boulder with a real-world data intensive academic experience through
work on a science project.

<div class='notice--success' markdown="1">

## <i class="fa fa-graduation-cap" aria-hidden="true"></i> Learning Objectives
At the end of your internship with Earth Lab you will have gained the following
skills:

* A better understanding of your research group's subject area
* Improved scientific writing skills
* Improved public speaking skills
* Accomplished the goals you set out for yourself at the start of the summer

</div>

Welcome to Earth Lab's internship program! The mission of our
internship is to immerse undergraduate students, in current
earth-systems research here at CU-Boulder. Our internship program will provide you
with experience

1. Presenting your science to various audiences
2. Writing a scientific abstract that summarizes your works
3. Finding data to address a research question, and
3. Working with data programmatically in tools like `R` and `Python`.

Through seminars, online training modules and working closely with
postdoctoral reseachers, faculty advisors, and the education team, you will learn
how to effectively communicate your research through writing and public speaking.

The end products of the internship include a midterm presentation and write-up
as well as a final presentation and paper. As an intern, you be evaluated and
given feedback on your writing and presentation skills as wells as the progress
you make on goals you set at the beginning of the semester.

  * A better understanding of your research group's subject area
  * Improved scientific writing skills
  * Improved public speaking skills
  * Accomplished the goals you set out for yourself at the start of the summer

## Assignments

There will be several assignments that are due throughout the semester. Criteria
for each assignment are below.

### Internship Goals Worksheet: Due May 26th
Criteria for each assignment you complete is summer are below. Detailed
information on how each assignment is evaluated will be provided in the seminars
and as the assignment due dates get closer.

## Midterm Project: Due June 30th
The midterm project includes an abstract and a presentation. Presentations
will be on **Friday June 30th 2017** and electronic copies of the abstract and
presentation are due by Midnight on June 30th 2017.

### 1a. Midterm Abstract

The mid term abstract should be 250-300 words and should include:

* *Background:* Briefly discuss the background of your research in the context of existing work and literature.
* *Methods / Study area:* Briefly descibe the methods you have been using and/or expect to use for your research this semester and the project study area.
* *Expected Results:* Summarize the results you expect to get from your research this semester.
* *Methods / Study area:* Briefly describe the methods you have been using
  and/or expect to use for your research this semester and the project study area.

### 1b. Midterm Abstract Presentation:*

Prepare a 10-minute presentation based you your abstract.

* Please minimize the amount of text on your slides. The more text on a slide,
the less your audience is listening to you!
* Be sure to carefully consider your audience and what they may or may not
know. You will give your presentation to the education team, your postdoctoral
adviser and each other. This audience will have a variety of background, so
avoid using discipline-specific "jargon" terms.

### Final Project: Due August 26th

The final project will consist of a scientific visualization and a presentation.
Please, use your imagination and come up with a creative way to visualize your
summer research.

## Work requirements

A key goal of the internship program is to fully immerse you in ongoing Earth Lab
research. To achieve this goal, we have the following expectations:

  * Spend all but two hours of your work hours in the Earth Lab office space.
  Earth Lab is *full* of knowledgeable people. Spending time in the office gives
  you the opportunity to collaborate with each other and other Earth Lab team
  members.
  * Meet you your postdoctoral adviser face-to-face at least once a week.
  This will ensure that your research stays on track and gives you time to ask
  them any questions you might have.
  * Meet with your faculty adviser at least twice during the semester. Faculty
  members are extremely busy, so work with them and your postdoctoral adviser to
  schedule meetings in advance. Meeting with them just prior to your midterm and
  final presentations will give you an opportunity to practice presenting before
  you present in front of others.
  * Participate in all research group meetings. Most lab groups have weekly
  meetings to discuss their current research and issues. This is a wonderful
  opportunity for you to participate in the research process.
